stages:
  - mavenbuild
  - maventest
  - autodeploy
#   - androidbuild
#   - androidtest
  
maven-build:
  stage: mavenbuild
  tags:
    - spring_tag
  script:
    - cd Backend
    - mvn package -B
    
maven-test:
  stage: maventest
  tags:
    - spring_tag
  script:
    - cd Backend
    - mvn test
  
autoDeploy:
  stage: autodeploy
  tags:
   - spring_tag
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
    
# android-build:
#   image: javiersantos/android-ci:latest
#   stage: androidbuild
#   before_script:
#     - export GRADLE_USER_HOME=`pwd`/.gradle
#     - chmod +x ./Minigames/gradlew
#   tags:
#   - android_tag
#   script:
#     - cd Minigames
#     - ./gradlew assemble
    
# unitTests:
#   image: javiersantos/android-ci:latest
#   stage: androidtest
#   before_script:
#     - export GRADLE_USER_HOME=`pwd`/.gradle
#     - chmod +x ./Minigames/gradlew
#   tags:
#   - android_tag
#   script:
#     - cd Minigames
#     - ./gradlew test
